### ISSUE TITLE
How to Include Alphine JS in a theme?

### ISSUE THREAD

**Issue by goldcoders** [bep/hugo-alpine-test#1]
Im im using this theme https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter

I npm install alphine js

on the theme partials heal.html

i added this
```
{ $alphinejs := resources.Get "js/app.js" | minify }}

<script type="text/javascript" src="{{ $alphinejs.Permalink }}"></script>
```
it work but i need to copy the the js file from node_modules/alphinejs/dist/alphine.js

and create app.js with the content from that file.

I saw you are using Hugo Modules...

But im fairly new to both Hugo and Go.

Can You Share me How can I Include alphine js as Hugo Modules?

where would i do hugo module init ?  on the theme root folder? or the exampleSite which has config.toml file.

next where would i import this module?

on config.toml file on exampleSite folder or will i add it on the theme.toml on root folder of theme or create a new config.toml file in the root folder of the theme...

lastly how would i import it on the head.html file 

hope you can help me thanks

**Comment by bep** [comment]
>it work but i need to copy the the js file from node_modules/alphinejs/dist/alphine.js

You could also mount the node_modules into your project. What's best/easiest depends a little. 

You have many questions that would fit better on https://discourse.gohugo.io/

This project works, though, and should be a good example on how to set it up.
