### ISSUE TITLE
can you create a version using tailwindcss?

### ISSUE THREAD

**Issue by goldcoders** [bep/hugo-alpine-test#2]
Hi is there a posibility that you would have a working example of tailwind ui with alpine js?

**Comment by bep** [comment]
I could and I will once I find some time.

**Comment by bep** [comment]
But looking at the Tailwund UI license, it does not permit "creating examples" (it seems): https://www.notion.so/Tailwind-UI-License-644418bb34ad4fa29aac9b82e956a867

But we should have a proper Tailwind + Alpine template repo.

**Comment by goldcoders** [comment]
would love to see a tailwind + alpine modules working together...
Hope you can keep me posted thanks
