### ISSUE TITLE
fresh clone does not start due to module errors

### ISSUE THREAD

**Issue by lschierer** [bep/hugo-alpine-test#3]
I am using hugo v0.101.0+extended darwin/arm64 BuildDate=unknown
as provided by homebrew.   I created a fresh checkout of this, because I wanted to compare what you have here against the errors I am getting when I try to transpile Alpinejs in my own hugo project (it compiles fine, but in the browser, I get errors).  
However, Hugo is unable to start in server mode, and I tracked it down to this, which I am unsure how to fix. 

```
hugo mod verify
go: github.com/gohugoio/hugo-mod-jslibs/alpinejs/v3@v3.0.0-20210902104917-6597e987c7ba: invalid version: unknown revision 6597e987c7ba
An unknown revision most likely means that someone has deleted the remote ref (e.g. with a force push to GitHub).
To resolve this, you need to manually edit your go.mod file and replace the version for the module in question with a valid ref.

The easiest is to just enter a valid branch name there, e.g. master, which would be what you put in place of 'v0.5.1' in the example below.

require github.com/gohugoio/hugo-mod-jslibs/instantpage v0.5.1

If you then run 'hugo mod graph' it should resolve itself to the most recent version (or commit if no semver versions are available).
Error: failed to download modules: failed to execute 'go [mod download]': failed to execute binary "go" with args [mod download]: go: github.com/gohugoio/hugo-mod-jslibs/alpinejs/v3@v3.0.0-20210902104917-6597e987c7ba: invalid version: unknown revision 6597e987c7ba
 *errors.errorString
```

**Comment by bep** [comment]
I have no clue what happened here, but Alpine is pointing to the wrong repo, you need to use https://github.com/gohugoio/hugo-mod-jslibs-dist/tree/main/alpinejs for Alpine v3. I don't have time to fix this repo, so I need to close this.
